version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000 # Frontend calls backend
      - VITE_HOST=0.0.0.0 # Ensure Vite listens externally
    depends_on:
      - backend
    volumes:
      - ./frontend:/app # Live code updates in dev

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - COUCHDB_URL=http://admin:password@couchdb:5984
      - DB_NAME=project
      - JWT_SECRET=d25d2d38003bc1afa4e685d62a0a0d58c7c5cdea0b27b7ce6938c04b41f81020
      - NODE_ENV=development
    depends_on:
      couchdb:
        condition: service_healthy
    volumes:
      - ./backend:/app

  couchdb:
    image: apache/couchdb:latest
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb-data:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 5s
      timeout: 5s
      retries: 10

  couchdb-setup:
    image: curlimages/curl:latest
    depends_on:
      couchdb:
        condition: service_healthy
    command: >
      sh -c "sleep 5 &&
             curl -X PUT http://admin:password@couchdb:5984/_users &&
             curl -X PUT http://admin:password@couchdb:5984/_replicator &&
             curl -X PUT http://admin:password@couchdb:5984/_global_changes &&
             curl -X PUT http://admin:password@couchdb:5984/project &&
             echo 'Databases created successfully'"

volumes:
  couchdb-data:
